# Training configuration
GPU: [0,1]

VERBOSE: False

MODEL:
  MODE: 'LET-llformer-LOL'

# Optimization arguments.
OPTIM:
  BATCH: 5
  EPOCHS: 200
  # EPOCH_DECAY: [10]
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 256 
  VAL_PS: 256
  TRAIN_DIR: './datasets/LOL/train'       # path to training data
  VAL_DIR: './datasets/LOL/test' # path to validation data
  #TRAIN_DIR: './datasets/MIT-5K/train'       # path to training data
  #VAL_DIR: './datasets/MIT-5K/test' # path to validation data
  SAVE_DIR: './checkpoints'           # path to save models and images
